name: PHP Code Sniffer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'
        extensions: sockets pdo_pgsql

    - name: Install Composer dependencies
      run: |
        cd $GITHUB_WORKSPACE/academico-php
        composer install --prefer-dist

    - name: PHPCS
      run: |
        cd $GITHUB_WORKSPACE/academico-php
        composer run phpcs
